services:
  data-generation-runner:
    image: hummingbot/quants-lab:latest
    volumes:
      - .:/quants-lab
    env_file:
      - .env
    command: conda run --no-capture-output -n quants-lab python3 tasks/trades_downloader_runner.py
    network_mode: host

  backtesting-runner:
    image: hummingbot/quants-lab:latest
    volumes:
      - .:/quants-lab
    deploy:
      replicas: 10
    env_file:
      - .env
    command: conda run --no-capture-output -n quants-lab python3 tasks/backtesting_runner.py
    network_mode: host

  candles-downloader-runner:
    image: hummingbot/quants-lab:latest
    volumes:
      - .:/quants-lab
    env_file:
      - .env
    command: conda run --no-capture-output -n quants-lab python3 tasks/candles_downloader_runner.py
    network_mode: host


  screeners-report-runner:
    image: hummingbot/quants-lab:latest
    volumes:
      - .:/quants-lab
    env_file:
      - .env
    command: conda run --no-capture-output -n quants-lab python3 tasks/report_runner.py
    network_mode: host
