name: quants-lab
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas-ta==0.3.14b
  - sqlalchemy
  - libcxx
  - pip
  - pip:
      - hummingbot
      - hummingbot-api-client
      - pycoingecko
      - geckoterminal-py==0.2.5
      - glom
      - defillama
      - statsmodels
      - numpy
      - pandas
      - plotly
      - jupyter
      - scikit-learn
      - pydantic
      - pyyaml
      - optuna
      - optuna-dashboard
      - pathlib
      - streamlit
      - pre-commit
      - isort
      - flake8
      - python-dotenv
      - asyncpg
      - psycopg2-binary
      - pyarrow
      - motor>=3.3.2
      - fastapi
      - uvicorn[standard]
      - croniter
      - pytz
      - papermill
      - nbformat
      - nbclient
      - kaleido
